# Generated by Django 2.2.5 on 2019-11-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20191108_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
