# Generated by Django 2.2.5 on 2019-11-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
