# Generated by Django 2.2.5 on 2019-11-16 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='privkey',
            field=models.CharField(default='pingpong', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='pubkey',
            field=models.CharField(default='pongping', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
