# Generated by Django 2.2.5 on 2019-12-02 01:51

from django.db import migrations, models
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20191115_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='pubkey',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='privkey',
            field=models.CharField(default=wallet.models.gen_wallet, max_length=64),
        ),
    ]
